### PR TITLE
Issue #00 fix: updating maven verify with clean verify

### PR DESCRIPTION
**Pull request by harshavardhanc**

### CODE REVIEW

**Comment by harshavardhanc** [comment]
PR looks good

**Comment by amorphous-1** [comment]
PR looks good

**Comment by amorphous-1** [comment]
@CIRCLE_PR_USERNAME Build Success

**Comment by amorphous-1** [comment]
@${CIRCLE_PR_USERNAME} Build Success

**Comment by amorphous-1** [comment]
${CIRCLE_PR_USERNAME} Build Success

**Comment by amorphous-1** [comment]
@harshavardhanc Build Success

**Pull request closed without merging**
